### ISSUE TITLE
Can the model change from yolov4 to yolo v3?

### ISSUE THREAD

**Issue by whitefoxcode** [jkjung-avt/yolov4_crowdhuman#10]
What i need to modified for using yolov3 instead of yolov4, Thanks.

**Comment by jkjung-avt** [comment]
You'd mainly need to write a custom yolov3 cfg file for that.  Reference: my [custom yolov4 cfg](https://github.com/jkjung-avt/yolov4_crowdhuman/blob/master/cfg/yolov4-crowdhuman-608x608.cfg) file in this repo.

In addition, you'd use [darknet53.conv.74](https://pjreddie.com/media/files/darknet53.conv.74) as the pre-trained weights.

Quote from [alexeyab/darknet](https://github.com/AlexeyAB/darknet):
> for yolov3.cfg, yolov3-spp.cfg (154 MB): darknet53.conv.74

**Comment by whitefoxcode** [comment]
can i use default yolov3 cfg for that?

**Comment by jkjung-avt** [comment]
> can i use default yolov3 cfg for that?

No.  The default yolov3 cfg is for COCO dataset (80 classes).

In addition, you'd better modify the anchors (for crowdhuman datatset) to get better results.

**Comment by whitefoxcode** [comment]
So i just need to change class to 2 class(face and full body) and the anchors right? one onether question sir, how do i get optimal anchor for crowdhuman dataset?

**Comment by jkjung-avt** [comment]
> how do i get optimal anchor for crowdhuman dataset?

Try `./darknet detector calc_anchors ...` command.  Refer to darknet documentation for details.

**Comment by whitefoxcode** [comment]
Thanks a lot sir, have a good day
