### ISSUE TITLE
Regarding Previous Request for the Yolov4_crowhuman weights

### ISSUE THREAD

**Issue by Jhc999** [jkjung-avt/yolov4_crowdhuman#15]
Hi, I noticed a previous request by a user for your trained weights and saw that you were able to send the weights over CowTransfer. Would it be possible for you to send the trained weights over CowTransfer as well? I tried to follow your tutorial to train the weights myself but I wasn't able to run the Colab notebook.

https://cowtransfer.com/s/d12286260a0e42

**Comment by jkjung-avt** [comment]
您有一份文件待查收！即刻点击链接获取文件：https://cowtransfer.com/s/5bcd5e0f54e644 或进入 cowtransfer.com 获取，在首页输入取件码：305959（24小时内有效）

**Comment by Jhc999** [comment]
Thank you so much!
