### ISSUE TITLE
请问能否提供416X416的weights测试用呢？

### ISSUE THREAD

**Issue by JohnnyHopp** [jkjung-avt/yolov4_crowdhuman#16]
Hi，jkjung. 我看到之前issues上有下载weights的连接，但是现在过期了，请问可以麻烦再发一下吗？416X416的weights就可以了，非常感谢！

**Comment by jkjung-avt** [comment]
https://drive.google.com/drive/folders/1otWzlnhDuYK-FWggPoZMQ8KmkxZMYS8N?usp=sharing
