### ISSUE TITLE
yolov4-tiny 416x416 trained weights?

### ISSUE THREAD

**Issue by kadirbeytorun** [jkjung-avt/yolov4_crowdhuman#17]
Hello, good job with the yolov4 instructions and sharing weights

Do you have yolov4 tiny trained weights as well? If so, could you share it and the corresponding cfg?

**Comment by jkjung-avt** [comment]
No.  I don't have trained yolov4-tiny models for the CrowdHuman dataset.  You should be able to train such as model by yourself easily and quickly.

**Comment by philipp-schmidt** [comment]
https://drive.google.com/file/d/1Vng1GL9mJf06z5gcahtSsinzrXajqmls/view?usp=sharing

cfg are in this repo

mAP is 56%

**Comment by kadirbeytorun** [comment]
@philipp-schmidt Thank you mate, really appreciate it :)

**Comment by SETIADEEPANSHU** [comment]
Hi @philipp-schmidt and @jkjung-avt really appreciate the efforts for helping the community. 

I have tried tiny yolov4-416 but it does not work great. Can you also please share the tiny version of yolov4-**608** (yolov4-tiny-crowdhuman-608x608.weights) or **tensorrt** version for Jetson Nano. I have Jetson (4GB) version but I am not able to convert tensorrt from onnx version despite changing max_workspace_size parameter (1 << 24) in the onnx_to_tensorrt.py. Can you please help?

**Comment by philipp-schmidt** [comment]
tiny 608x608 has only very little mAP improvement compared to tiny 416x416.

Try tiny-416x416-3l, training is very fast and does not need much vram.

**Comment by philipp-schmidt** [comment]
Send me a mail for weights, p.schmidt@isarsoft.com

**Comment by hoangkhoiLE** [comment]
@jkjung-avt @philipp-schmidt  Thank both of you for the excellent work.
@philipp-schmidt Can you share  me the weights of tiny-416x416-3l model ? Is  tiny-416x416-3l better at accuracy than tiny-416x416 ? Thank you in advance !
