### ISSUE TITLE
can you release you trained weight?

### ISSUE THREAD

**Issue by simplew2011** [jkjung-avt/yolov4_crowdhuman#2]
Hi,i recently do some research in CrowdHuman detection, can you release your trained weight, i want do some test.
thanks.

**Comment by jkjung-avt** [comment]
Please provide a place (Google Drive or something similar) for me to upload the files.  Roughly 250MB of space is required.

**Comment by simplew2011** [comment]
nice to you, answer my question.
you can use this website to share your files：
https://cowtransfer.com/
when you upload you weight file, you will set to share, by a link or a code.
then comment this issue, so i can download this.
I'm very grateful to you for all your help

**Comment by simplew2011** [comment]
Cannot access Google Cloud Drive in China，so,
Sending by mail may be more convenient：
1327431557@qq.com

**Comment by jkjung-avt** [comment]
https://cowtransfer.com/s/d12286260a0e42
Access code: 2zji6j

(The web site says the code is only valid for 24 hours.)

**Comment by simplew2011** [comment]
> https://cowtransfer.com/s/d12286260a0e42
> Access code: 2zji6j
> 
> (The web site says the code is only valid for 24 hours.)

thanks.
