### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by aloosh12** [jkjung-avt/yolov4_crowdhuman#23]
w can't get data in google colab could you change the permission of your drive for dataset folders
Downloading CrowdHuman_train01.zip...
Permission denied: https://drive.google.com/uc?id=134QOvaatwKdy0iIeNqA_p-xkAhkV4F8Y
Maybe you need to change permission over 'Anyone with the link'?

**Comment by jkjung-avt** [comment]
That particular Google Drive link is owned by https://www.crowdhuman.org/, not me.  I'm not able to change the permission for you.

In fact, you get "permission denied" error most likely due to you access the file too many times in a short period.  You could try again later.

**Comment by aloosh12** [comment]
Thank you. I'll try later
