### ISSUE TITLE
How do I create a .odgt extension file to create a custom yolov4 model?

### ISSUE THREAD

**Issue by Choikyungho9** [jkjung-avt/yolov4_crowdhuman#25]
How do I create a .odgt extension file to create a custom yolov4 model?

I am following your tutorial on google colab.

But I saw odgt extension files for the first time in my life in the dataset.

This file is like a annotation file. Please tell me how to create odgt file to make custom yolov4 .

**Comment by jkjung-avt** [comment]
You don't need to use odgt file format, which is pretty uniquely defined by the CrowdHuman dataset.

Instead, just follow [How to train (to detect your custom objects)](https://github.com/AlexeyAB/darknet#how-to-train-to-detect-your-custom-objects) in the original DarkNet README and create .txt files.  This tutorial also converts odgt to DarkNet txt.

**Comment by Choikyungho9** [comment]
Thank you. I'll try.
