### ISSUE TITLE
Training on Xavier agx - make issue

### ISSUE THREAD

**Issue by hmkim97** [jkjung-avt/yolov4_crowdhuman#27]
hello!

I tried to train on Xavier agx but there's an error on it. 

when I 'make' after modifying Makefile, 

chmod +x *.sh
g++ -std=c++11 -std=c++11 -Iinclude/ -I3rdparty/stb/include -DOPENCV `pkg-config --cflags opencv4 2> /dev/null || pkg-config -                      -cflags opencv` -DGPU -I/usr/local/cuda/include/ -DCUDNN -DCUDNN_HALF -Wall -Wfatal-errors -Wno-unused-result -Wno-unknown-pra                      gmas -fPIC -ffp-contract=fast -mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a -Ofast -DOPENCV -fopenmp -DGPU -DCUDNN -I/usr/loca                      l/cudnn/include -DCUDNN_HALF -fPIC -c ./src/image_opencv.cpp -o obj/image_opencv.o
g++: error: unrecognized command line option ‘-mavx’
g++: error: unrecognized command line option ‘-mavx2’
g++: error: unrecognized command line option ‘-msse3’
g++: error: unrecognized command line option ‘-msse4.1’
g++: error: unrecognized command line option ‘-msse4.2’
g++: error: unrecognized command line option ‘-msse4a’
Makefile:182: recipe for target 'obj/image_opencv.o' failed
make: *** [obj/image_opencv.o] Error 1

error like this.

My agx's environment like this:

 - NVIDIA Jetson AGX Xavier [16GB]
   * Jetpack 4.5.1 [L4T 32.5.1]
   * NV Power Mode: MODE_15W_DESKTOP - Type: 7
   * jetson_stats.service: active
 - Libraries:
   * CUDA: 10.2.89
   * cuDNN: 8.0.0.180
   * TensorRT: 7.1.3.0
   * Visionworks: 1.6.0.501
   * OpenCV: 4.1.1
   * VPI: ii libnvvpi1 1.0.15 arm64 NVIDIA Vision Programming Interface library
   * Vulkan: 1.2.70

I'm always grateful for your good materials.

**Comment by jkjung-avt** [comment]
1. Jetson AGX Xavier is an inference platform.  NVIDIA certainly doesn't recommend users to do DL model training on it.
2. The "-mavx -mavx2 -msse3 -msse4.1 -msse4.2 -msse4a" command-line options for gcc are for x86.  I think you could try to remove those in the Makefile.

**Comment by hmkim97** [comment]
Thanks to you, I solved it well. Thank you!
