### ISSUE TITLE
Can you share your weights files?

### ISSUE THREAD

**Issue by Tsings04** [jkjung-avt/yolov4_crowdhuman#3]
Hi jkjung,

I have also train my custom yolov4 on this dataset, but can not achieve with good performance. Could you share your weights files for 608x608? I would like to continue my training on your works, thanks a lot in advance!

**Comment by jkjung-avt** [comment]
Please provide a place (say, Google Drive) for me to upload the weights.  It's about 245MB in size.

**Comment by Tsings04** [comment]
> Please provide a place (say, Google Drive) for me to upload the weights. It's about 245MB in size.

Yep, Google Drive would be fine. thank you so much for such quick reply :) :+1:

**Comment by jkjung-avt** [comment]
Nope, my Google Drive doesn't have much space left.  I need you to provide a place for me to upload the file.

**Comment by Tsings04** [comment]
> Nope, my Google Drive doesn't have much space left. I need you to provide a place for me to upload the file.

Sorry i didn't get it. I have create a share folder on my Google Drive and there should be more than 1GB space. You could use it with the link [here](https://drive.google.com/drive/folders/1lEiSimWDLVxAszaFlweXfylIgYSwdnZt?usp=sharing)

**Comment by jkjung-avt** [comment]
Done.  I have just uploaded "yolov4-crowdhuman-608x608_best.weights".

**Comment by Tsings04** [comment]
> Done. I have just uploaded "yolov4-crowdhuman-608x608_best.weights".

I saw it, thank you so much! :+1:

**Comment by maiff** [comment]
@Tsings04 Could you share the  weights files for 608x608？ Thanks~
