### ISSUE TITLE
max_batches value

### ISSUE THREAD

**Issue by dlavrantonis** [jkjung-avt/yolov4_crowdhuman#30]
This is more a question than an issue.
Since the crowdhuman608x608 dataset contains around 15000 photos for training, why is the max_batches set to 6000 only?
In the instructions of yolov4 there is a guideline saying that the max_batches shall be at least equal to the number of your training images.

**Comment by jkjung-avt** [comment]
Refer to [yolov4-crowdhuman-608x608.cfg](https://github.com/jkjung-avt/yolov4_crowdhuman/blob/master/cfg/yolov4-crowdhuman-608x608.cfg):

* `batch=64`  (stack 64 images as a batch/iteration during training)
* `max_batches=6000`
* So the total number of images used during training = 64 * 6,000 = 384,000

In fact, I determined the number 6,000 by looking at the "loss curve".   Training the model longer probably doesn't help (lowering the loss) much.

![](https://raw.githubusercontent.com/jkjung-avt/yolov4_crowdhuman/master/doc/chart_yolov4-crowdhuman-608x608.png)

**Comment by dlavrantonis** [comment]
thanks!
