### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by mnurilmi** [jkjung-avt/yolov4_crowdhuman#31]
hi, thanks for your repo. This is very helpful. However, I still don't understand about the purpose of Kmeans on your data preparation. Does it affect the quality of the dataset?

**Comment by mnurilmi** [comment]
anw, I've tried using this dataset with yolov7, but the result of objectness loss is sucks. Apart from that, the results are quite satisfactory. My assumption is in the dataset. With the same configuration, I used a bit of the person image dataset and objectness loss just fine. 
Hopefully u read and respond to this question. thank you

**Comment by jkjung-avt** [comment]
> hi, thanks for your repo. This is very helpful. However, I still don't understand about the purpose of Kmeans on your data preparation. Does it affect the quality of the dataset?

The K-means is just an experiment by myself.  I would suggest you to follow the instruction of the original yolov4 repo ([AlexeyAB/darknet](https://github.com/AlexeyAB/darknet)):

_To calculate anchors: `./darknet detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416`_

**Comment by mnurilmi** [comment]
ok thanks for the response...for now, I'm using your code and adapting some instructions. So I totally depend on the yolov7 algorithm to do the autoanchor... but overall, my code is based on your repo pipeline
