### ISSUE TITLE
Trained Weights

### ISSUE THREAD

**Issue by ashtanzk** [jkjung-avt/yolov4_crowdhuman#4]
Hi, appreciate your effort in uploading this repo. Would it be possible if you could share your trained weights with me? Here is a Google Drive [link](https://drive.google.com/drive/folders/1VJDz-zcE5lYRfoG-TIDUWvZ2u8HxyjYG?usp=sharing)

Thank you so much

**Comment by jkjung-avt** [comment]
Sure.  I have just uploaded "yolov4-crowdhuman-608x608_best.weights" onto your Google Drive folder.

**Comment by ashtanzk** [comment]
Thank you so much! I appreciate it!
