### ISSUE TITLE
Can you send me the model weights?

### ISSUE THREAD

**Issue by zt1112** [jkjung-avt/yolov4_crowdhuman#5]
Can you send me the model weights to my e-mail?
Thank a lot!!

E-mail: 441869213@qq.com

**Comment by jkjung-avt** [comment]
The "yolov4-crowdhuman-608x608_best.weights" file is about 245MB in size.  It is too large to be attached in an email.

**Comment by zt1112** [comment]
> The "yolov4-crowdhuman-608x608_best.weights" file is about 245MB in size. It is too large to be attached in an email.

Thanks for your reply. Here is my google drive [link](https://drive.google.com/drive/folders/1EhFzSczxd9ZO_bkHZZNhY-lKi_K3St0V?usp=sharing).

**Comment by jkjung-avt** [comment]
I have just uploaded "yolov4-crowdhuman-608x608_best.weights".
