### ISSUE TITLE
can this work on deepstream

### ISSUE THREAD

**Issue by aniketvartak** [jkjung-avt/yolov4_crowdhuman#6]
I have trained the model using your method and also able to run it on the nano/nx.
Would the trt converted model directly run using deepstream or would I have to do any additional convesions?!
thanks!

**Comment by jkjung-avt** [comment]
Custom trained yolov4 models using this repository are just standard darknet models.  They are the exact same architecture as the original darknet yolov4 coco model.  It should be possible to convert these custom trained yolov4 models to TensorRT engines and use DeepStream SDK to do inference.

**Comment by aniketvartak** [comment]
Thanks JK,
I was able to convert this and run by adding yolov4 specific code..
