### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by GraceKafuu** [jkjung-avt/yolov4_crowdhuman#7]
经常能看见你的身影~~感谢，你的每个教程都很好！

这个数数据集没有了，不能下载，你能不能提供一下，谢谢！

**Comment by jkjung-avt** [comment]
謝謝你的誇獎。

我並沒有CrowdHuman dataset的所有權，請你可透過CrowdHuman官網上的聯結自行下載檔案。

https://www.crowdhuman.org/download.html
