### ISSUE TITLE
ERROR WHILE TESTING ON A LOCAL VIDEO FILE

### ISSUE THREAD

**Issue by bobbilichandu** [jkjung-avt/yolov4_crowdhuman#9]
While testing on a local video file. I came across this error
"""
double free or corruption (!prev)
Aborted (core dumped)
"""
 command used : python3 darknet_video.py --input videos/case1.mp4 --out_filename videos_output/case1.avi --weights ./backup/yolov4-crowdhuman-608x608_final.weights --dont_show --ext_output --config_file ./cfg/yolov4-crowdhuman-608x608.cfg --data_file ../data/crowdhuman-608x608.data --thresh 0.25

I double checked every parameter. weights are loaded properly. 

[yolo] params: iou loss: ciou (4), iou_norm: 0.07, obj_norm: 1.00, cls_norm: 1.00, delta_norm: 1.00, scale_x_y: 1.05
nms_kind: greedynms (1), beta = 0.600000 
Total BFLOPS 127.248 
avg_outputs = 1046494 
 Allocate additional workspace_size = 52.43 MB 
 Try to load weights: ./backup/yolov4-crowdhuman-608x608_final.weights 
Loading weights from ./backup/yolov4-crowdhuman-608x608_final.weights...
 seen 64, trained: 384 K-images (6 Kilo-batches_64) 
Done! Loaded 162 layers from weights-file 
Loaded - names_list: data/crowdhuman.names, classes = 2 
videos/case1.mp4
FPS: 4

Objects:
person: 50.31%    (left_x: 250   top_y:  59   width:   7   height:  33)
person: 88.72%    (left_x: 259   top_y:  60   width:   9   height:  34)
FPS: 26

Objects:
person: 49.94%    (left_x: 250   top_y:  59   width:   7   height:  33)
person: 88.43%    (left_x: 259   top_y:  60   width:   9   height:  34)
double free or corruption (!prev)
Aborted (core dumped)

How to solve this issue?

**Comment by jkjung-avt** [comment]
I myself have never used "darknet_video.py".  Have you tried the "darknet" executable instead?

**Comment by bobbilichandu** [comment]
darknet executable is working good enough. But can't save the video output using executable. we can see the output that detection is happening, but can't see the output video.

**Comment by jkjung-avt** [comment]
I think you could report the issue to the maintainer of "darknet_video.py".
